# Generated by Django 2.2 on 2019-05-21 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=256)),
                ("note", models.TextField(blank=True, default=None)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=256)),
                ("note", models.TextField(blank=True, default=None)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="StatisticsRowStatistics",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("parent_statistics", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.Statistics")),
                ("statistics", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="child_statistics", to="core.Statistics")),
            ],
        ),
        migrations.CreateModel(
            name="StatisticsRowRegister",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("parent_statistics", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.Statistics")),
                ("register", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.Register")),
            ],
        ),
        migrations.CreateModel(
            name="RegisterRow",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("description", models.CharField(max_length=256)),
                ("period", models.CharField(blank=True, default=None, max_length=256)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.TextField(blank=True, default=None)),
                ("register", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.Register")),
            ],
        ),
    ]
